RainbowWine/Controllers/ProductDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using RainbowWine.Data;
using RainbowWine.Services;
using RainbowWine.Services.DBO;
using RainbowWine.Services.Filters;

namespace RainbowWine.Controllers
{
    [AuthorizeSpirit]
    public class ProductDetailsController : Controller
    {
        private rainbowwineEntities db = new rainbowwineEntities();

        [AuthorizeSpirit(Roles = "Shopper")]
        // GET: ProductDetails
        public ActionResult Index()
        {
            ViewBag.HostName = Request.Url.GetLeftPart(UriPartial.Authority);
            return View(db.ProductDetails.ToList());
        }

        [AuthorizeSpirit(Roles = "Shopper")]
        // GET: ProductDetails/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductDetail productDetail = db.ProductDetails.Find(id);
            if (productDetail == null)
            {
                return HttpNotFound();
            }
            ViewBag.HostName = Request.Url.GetLeftPart(UriPartial.Authority);
            return View(productDetail);
        }

        [AuthorizeSpirit(Roles = "Shopper")]
        // GET: ProductDetails/Create
        public ActionResult Create()
        {
            return View();
        }



        [AuthorizeSpirit(Roles = "Shopper")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductID,ProductName,Size,Category,ProductType,Price,ShopItemId,CreatedDate,ModifiedDate,IsDelete")] ProductDetail productDetail, HttpPostedFileBase Image, HttpPostedFileBase ThumbImage)
        {
            if (ModelState.IsValid)
            {
                productDetail.CreatedDate = DateTime.Now;
                productDetail.ModifiedDate = DateTime.Now;
                productDetail.IsDelete = productDetail.IsDelete;

                if (Image.ContentLength > 0) productDetail.ProductImage = SpiritUtility.UploadSpiritFile(Image, "/Content/images/product", "prod-image");
                if (ThumbImage.ContentLength > 0) productDetail.ProductThumbImage = SpiritUtility.UploadSpiritFile(ThumbImage, "/Content/images/product", "prod-thumb");

                db.ProductDetails.Add(productDetail);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(productDetail);
        }


        [AuthorizeSpirit(Roles = "Shopper")]
        // GET: ProductDetails/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductDetail productDetail = db.ProductDetails.Find(id);
            if (productDetail == null)
            {
                return HttpNotFound();
            }
            return View(productDetail);
        }

        // POST: ProductDetails/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.

        [AuthorizeSpirit(Roles = "Shopper")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductID,ProductName,Size,Category,ProductType,Price,ShopItemId,IsDelete")] ProductDetail productDetail, HttpPostedFileBase Image, HttpPostedFileBase ThumbImage)
        {
            if (ModelState.IsValid)
            {
                ProductDetail pd = db.ProductDetails.Find(productDetail.ProductID);
                pd.ProductName = productDetail.ProductName;
                pd.Size = productDetail.Size;
                pd.Category = productDetail.Category;
                pd.ProductType = productDetail.ProductType;
                pd.Price = productDetail.Price;
                pd.ShopItemId = productDetail.ShopItemId;
                pd.ModifiedDate = DateTime.Now;
                pd.IsDelete = productDetail.IsDelete;

                if (Image != null && Image.ContentLength > 0) pd.ProductImage = SpiritUtility.UploadSpiritFile(Image, "/Content/images/product", "prod-image");
                if (ThumbImage != null && ThumbImage.ContentLength > 0) pd.ProductThumbImage = SpiritUtility.UploadSpiritFile(ThumbImage, "/Content/images/product", "prod-thumb");

                db.Entry(pd).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(productDetail);
        }


        [AuthorizeSpirit(Roles = "Shopper")]
        // GET: ProductDetails/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductDetail productDetail = db.ProductDetails.Find(id);
            if (productDetail == null)
            {
                return HttpNotFound();
            }
            return View(productDetail);
        }

        [AuthorizeSpirit(Roles = "Shopper")]
        // POST: ProductDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProductDetail productDetail = db.ProductDetails.Find(id);
            db.ProductDetails.Remove(productDetail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpGet]
        [AuthorizeSpirit(Roles = "SalesManager, Shopper")]
        public ActionResult Notify(bool chkPremium=true)
        {
            NotifyDBO notifyDBO = new NotifyDBO();
            var notify=notifyDBO.Notifies(chkPremium);
            ViewBag.IsPremium = chkPremium;
            return View(notify);
        }

        [HttpPost]
        [AuthorizeSpirit(Roles = "SalesManager, Shopper")]
        public ActionResult NotifyCalled(NotifyHandle notifyHandle)
        {
            if (notifyHandle.NotifyId <= 0)
            {
                return Json(new { msg="Notify is not selected.", status=false}, JsonRequestBehavior.AllowGet);
            }

            var nHandle = new NotifyHandle
            {
                CreatedDate = DateTime.Now,
                NotifyId = notifyHandle.NotifyId,
                Remark = notifyHandle.Remark,
                UserId = User.Identity.GetUserId()
            };
            db.NotifyHandles.Add(nHandle);
            var notify = db.Notifies.Find(notifyHandle.NotifyId);
            notify.ModifiedDate = DateTime.Now;
            notify.IsNotified = true;
            db.SaveChanges();

            return Json(new { msg = "Notify updated successfully.", status = true }, JsonRequestBehavior.AllowGet);
        }
    }
}

RainbowWine/Views/ProductDetails/Create.cshtml
@model RainbowWine.Data.ProductDetail

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "ProductDetails", FormMethod.Post, 
                             new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ProductDetail</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Size, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Size, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShopItemId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShopItemId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShopItemId, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedDate, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.ProductImage,"Product Image", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.ProductImage, new { htmlAttributes = new { @class = "form-control" } })*@
                <input type="file" name="Image" id="Image"/>
                @Html.ValidationMessageFor(model => model.ProductImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductThumbImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.ProductThumbImage, new { htmlAttributes = new { @class = "form-control" } })*@
                <input type="file" name="ThumbImage" id="ThumbImage"/>
                @Html.ValidationMessageFor(model => model.ProductThumbImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsDelete, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsDelete)
                    @Html.ValidationMessageFor(model => model.IsDelete, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" onclick="javascript: return SubmitForm();"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section scripts{
    <script>
        function SubmitForm() {
            if (confirm('Are you sure do you want to update the Product.'))
                return true;

            return false;
        }

    </script>
}

RainbowWine/Views/ProductDetails/Delete.cshtml
@model RainbowWine.Data.ProductDetail

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProductDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Size)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Size)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShopItemId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShopItemId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductImage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductThumbImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductThumbImage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDelete)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDelete)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RainbowWine/Views/ProductDetails/Details.cshtml
@model RainbowWine.Data.ProductDetail

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ProductDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Size)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Size)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShopItemId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShopItemId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductImage)
        </dt>

        <dd>
            <a target="_blank" href="@( ViewBag.HostName + Model.ProductImage)">@Model.ProductImage</a>
            @*@Html.DisplayFor(model => model.ProductImage)*@
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductThumbImage)
        </dt>

        <dd>
            <a target="_blank" href="@( ViewBag.HostName + Model.ProductThumbImage)">@Model.ProductThumbImage</a>
            @*@Html.DisplayFor(model => model.ProductThumbImage)*@
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDelete)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDelete)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProductID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RainbowWine/Views/ProductDetails/Edit.cshtml
@model RainbowWine.Data.ProductDetail

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "ProductDetails", FormMethod.Post, 
                             new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ProductDetail</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProductID)

        <div class="form-group">
            @Html.LabelFor(model => model.ProductName,"Product Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Size, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Size, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductType,"Product Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShopItemId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShopItemId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShopItemId, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedDate, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.ProductImage,"Product Image", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.ProductImage, new { htmlAttributes = new { @class = "form-control" } })*@
                <input type="file" name="Image" id="Image" />
                @Html.ValidationMessageFor(model => model.ProductImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductThumbImage,"Product Thumb Image", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.ProductThumbImage, new { htmlAttributes = new { @class = "form-control" } })*@
                <input type="file" name="ThumbImage" id="ThumbImage" />
                @Html.ValidationMessageFor(model => model.ProductThumbImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsDelete, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsDelete)
                    @Html.ValidationMessageFor(model => model.IsDelete, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" onclick="javascript: return SubmitForm();" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section scripts{
    <script>
        function SubmitForm() {
            if (confirm('Are you sure do you want to update the Product.'))
                return true;

            return false;
        }

    </script>
}

RainbowWine/Views/ProductDetails/Index.cshtml
@model IEnumerable<RainbowWine.Data.ProductDetail>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProductID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Size)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShopItemId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductImage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductThumbImage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsDelete)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.ProductID)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.ProductName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Size)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Category)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.ProductType)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Price)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.ShopItemId)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.CreatedDate)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.ModifiedDate)
    </td>
    <td>
        <a target="_blank" href="@( ViewBag.HostName + item.ProductImage)">@item.ProductImage</a>
    </td>
    <td>
        <a target="_blank" href="@( ViewBag.HostName + item.ProductThumbImage)">@item.ProductThumbImage</a>
        @*@Html.DisplayFor(modelItem => item.ProductThumbImage)*@
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.IsDelete)
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.ProductID }) |
        @Html.ActionLink("Details", "Details", new { id = item.ProductID }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.ProductID })
    </td>
</tr>
}

</table>