RainbowWine/Controllers/DeliveryAgentsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using RainbowWine.Data;
using RainbowWine.Models;
using RainbowWine.Services;
using RainbowWine.Services.DBO;
using RainbowWine.Services.DO;
using RainbowWine.Services.Filters;
using System.Data;
using System.Data.SqlClient;
using RainbowWine.Providers;
using SZInfrastructure;

namespace RainbowWine.Controllers
{
    [AuthorizeSpirit]
    [StopAction]
    public class DeliveryAgentsController : Controller
    {
        private rainbowwineEntities db = new rainbowwineEntities();

        [HttpPost]
        [Route("callback_api")]
        [AllowAnonymous]
        public ActionResult CallbackPush(CallbackPushApi callbackPushApi)
        {
            try
            {
                db.CallbackPushApis.Add(callbackPushApi);
                db.SaveChanges();
            }
            catch { return Json(new { message = "Fail", status = "1" }, JsonRequestBehavior.AllowGet); }

            return Json(new { message = "Success", status = "0" }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [Route("~/send_app_sms/{phonenumber}")]
        [AllowAnonymous]
        public ActionResult SendSMSToCustomer(string mType, string phonenumber)
        {
            try
            {
                if (!string.IsNullOrWhiteSpace(phonenumber))
                {
                    WSendSMS wsms = new WSendSMS();
                    string textmsg = string.Format(ConfigurationManager.AppSettings["SendSMSToCust"]);
                    wsms.SendMessage(textmsg, phonenumber);
                }
            }
            catch { return Json(new { message = "Fail", status = "1" }, JsonRequestBehavior.AllowGet); }

            return Json(new { message = "Success", status = "0" }, JsonRequestBehavior.AllowGet);
        }

        [AuthorizeSpirit(Roles = "DeliveryManager")]
        public ActionResult Index()
        {
            var deliveryAgents = db.DeliveryAgents.Include(d => d.WineShop).Include(d => d.WineShop.DeliveryZones).ToList();
            return View(deliveryAgents);
        }

        [AuthorizeSpirit(Roles = "DeliveryManager")]
        public ActionResult LoginDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // var deliveryAgentLogin = db.DeliveryAgentLogins.Include(o => o.DeliveryAgent).Where(o => o.DeliveryAgentId == id).OrderByDescending(o => o.Id).Take(100);
            var deliveryAgentLogin = db.DeliveryAgentLogins.Include(o => o.DeliveryAgent).Where(o => o.DeliveryAgentId == id).OrderByDescending(o => o.OnDuty).ThenByDescending(d => d.OnDuty).Take(100);

            if (deliveryAgentLogin == null)
            {
                return HttpNotFound();
            }
            return View(deliveryAgentLogin.ToList());
        }

        [AuthorizeSpirit(Roles = "DeliveryManager")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DeliveryAgent deliveryAgent = db.DeliveryAgents.Find(id);
            if (deliveryAgent == null)
            {
                return HttpNotFound();
            }
            return View(deliveryAgent);
        }

        [AuthorizeSpirit(Roles = "DeliveryManager")]
        public ActionResult Create()
        {
            ViewBag.DeliverySlotID = new SelectList(db.DeliverySlots, "DeliverySlotID", "DeliverySlotID");
            ViewBag.ShopID = new SelectList(db.WineShops, "Id", "ShopName");
           // ViewBag.DeliveryAgentTypeId = new SelectList(db.DeliveryAgentTypes, "DeliveryAgentTypeId", "Descriptions");   // ShiptName
            ViewBag.WeekOffs = new SelectList(db.WeekDays, "Id", "DayName");

          var data = (from s in db.DeliveryAgentTypes                     
                     select new { DeliveryAgentTypeId=s.DeliveryAgentTypeId, Descriptions = s.Descriptions +"_" + s.ShiptName }).ToList();
            ViewBag.DeliveryAgentTypeId = new SelectList(data, "DeliveryAgentTypeId", "Descriptions");

            return View();
        }

        [AuthorizeSpirit(Roles = "DeliveryManager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,DeliveryExecName,ShopID,LastDeliveryOn,Contact,Address,TravelMode,Coverage,DeliverySlotID,IsAtShop,ExciseID,DocPath,WeekOffs,DeliveryAgentTypeId")] DeliveryAgent deliveryAgent, string [] WeekOffs, HttpPostedFileBase file)
        {

            string result = string.Empty;
            if (WeekOffs != null)
            {
                foreach (var entry in WeekOffs)
                {
                    result += entry + ',';
                }
            }
            deliveryAgent.WeekOffs = result;
            if (ModelState.IsValid)
            {
                deliveryAgent.isActive = 1;
                db.DeliveryAgents.Add(deliveryAgent);
                db.SaveChanges();
                if (file!=null && file.ContentLength > 0)
                {
                    string qrImagePtath = $"/Content/images/delivery";
                    string path = Server.MapPath($"~{qrImagePtath}");
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }
                    qrImagePtath = $"{qrImagePtath}/{deliveryAgent.Id}";
                    path = Server.MapPath($"~{qrImagePtath}");
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }
                    Guid newguid = Guid.NewGuid();
                    string fname = file.FileName;
                    string extention = fname.Substring(fname.LastIndexOf("."));
                    qrImagePtath = $"{qrImagePtath}/{Convert.ToString(deliveryAgent.Id)}-{newguid.ToString()}{extention}";
                    path = Server.MapPath($"~{qrImagePtath}");
                    file.SaveAs(path);

                    deliveryAgent.DocPath = qrImagePtath;
                    db.SaveChanges();
                }
                return RedirectToAction("List");
            }

            ViewBag.DeliverySlotID = new SelectList(db.DeliverySlots, "DeliverySlotID", "DeliverySlotID", deliveryAgent.DeliverySlotID);
            ViewBag.ShopID = new SelectList(db.WineShops, "Id", "ShopName", deliveryAgent.ShopID);
           // ViewBag.DeliveryAgentTypeId = new SelectList(db.DeliveryAgentTypes, "DeliveryAgentTypeId", "Descriptions");   // ShiptName
            ViewBag.WeekOffs = new SelectList(db.WeekDays, "Id", "DayName");

            var data = (from s in db.DeliveryAgentTypes
                        select new { DeliveryAgentTypeId = s.DeliveryAgentTypeId, Descriptions = s.Descriptions + "_" + s.ShiptName }).ToList();
            ViewBag.DeliveryAgentTypeId = new SelectList(data, "DeliveryAgentTypeId", "Descriptions");

            return View(deliveryAgent);
        }

        [AuthorizeSpirit(Roles = "DeliveryManager")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DeliveryAgent deliveryAgent = db.DeliveryAgents.Find(id);
            if (deliveryAgent == null)
            {
                return HttpNotFound();
            }
            ViewBag.DeliverySlotID = new SelectList(db.DeliverySlots, "DeliverySlotID", "DeliverySlotID", deliveryAgent.DeliverySlotID);
            ViewBag.ShopID = new SelectList(db.WineShops, "Id", "ShopName", deliveryAgent.ShopID);
            return View(deliveryAgent);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,DeliveryExecName,ShopID,LastDeliveryOn,Contact,Address,TravelMode,Coverage,DeliverySlotID,IsAtShop,ExciseID,DocPath")] DeliveryAgent deliveryAgent)
        {
            if (ModelState.IsValid)
            {
                db.Entry(deliveryAgent).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DeliverySlotID = new SelectList(db.DeliverySlots, "DeliverySlotID", "DeliverySlotID", deliveryAgent.DeliverySlotID);
            ViewBag.ShopID = new SelectList(db.WineShops, "Id", "ShopName", deliveryAgent.ShopID);
            return View(deliveryAgent);
        }

        [AuthorizeSpirit(Roles = "DeliveryManager")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DeliveryAgent deliveryAgent = db.DeliveryAgents.Find(id);
            if (deliveryAgent == null)
            {
                return HttpNotFound();
            }
            return View(deliveryAgent);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DeliveryAgent deliveryAgent = db.DeliveryAgents.Find(id);
            db.DeliveryAgents.Remove(deliveryAgent);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        [HttpGet]
        [AuthorizeSpirit(Roles = "Deliver")]
        public ActionResult OnOffDuty(int duty)
        {

RainbowWine/Views/DeliveryAgents/Analytics.cshtml
@{
    ViewBag.Title = "Analytics";
}

<h2>Analytics</h2>

@section scripts{
    <script>
        window.location = "@ViewBag.QlikUrl";
    </script>
    }

RainbowWine/Views/DeliveryAgents/AnalyticsLoad.cshtml
@{
    ViewBag.Title = "AnalyticsLoad";
}

<h2>Analytics</h2>
@section scripts{
    <script src="https://ec2amaz-j836kgo.qonverse.ai/resources/assets/external/requirejs/require.js"></script>
    <script src="~/Scripts/requireJS.js"></script>
    <script>
        var requireJsConfig = {
            host: "ec2amaz-j836kgo.qonverse.ai",
            prefix: '/',
            port: '',//443,
            isSecure: true
        };

        //var app = qlikLoad.openApp(qAppId, this.requireJsConfig);
    </script>
}
<iframe width="100%" height="600" frameborder="0" src="https://ec2amaz-cp0fntp.spiritzone.in/single/?appid=73b61c0f-4bff-48a1-974d-080d30dee06b&sheet=b3aab5ac-5100-45c6-bd61-4d18a094d280&select=clearall"></iframe>

RainbowWine/Views/DeliveryAgents/Create.cshtml
@model RainbowWine.Data.DeliveryAgent

@{
    ViewBag.Title = "Create";
}


<h2>Create</h2>

@using (Html.BeginForm("Create","DeliveryAgents",FormMethod.Post,new { enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>DeliveryAgent</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.Label("Delivery Agent Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DeliveryExecName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DeliveryExecName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ShopID, "Shop", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ShopID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ShopID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastDeliveryOn, "Last Delivery On", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastDeliveryOn, new { htmlAttributes = new { @class = "form-control", @placeholder = "yyyy-MM-dd" } })
            @Html.ValidationMessageFor(model => model.LastDeliveryOn, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DeliveryAgentTypeId, "Delivery Agent Type", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("DeliveryAgentTypeId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.DeliveryAgentTypeId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.WeekOffs, "Week Off", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("WeekOffs", null, htmlAttributes: new { @class = "form-control", @multiple = "multiple" })
            @Html.ValidationMessageFor(model => model.WeekOffs, "", new { @class = "text-danger" })


        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Contact, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Contact, new { htmlAttributes = new { @class = "form-control", @maxlength = "10" } })
            @Html.ValidationMessageFor(model => model.Contact, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" , @maxlength = "2000" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TravelMode, "Travel Mode", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TravelMode, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TravelMode, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Coverage, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Coverage, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Coverage, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DeliverySlotID, "Delivery Slot", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("DeliverySlotID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.DeliverySlotID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IsAtShop, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.IsAtShop)
                @Html.ValidationMessageFor(model => model.IsAtShop, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ExciseID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ExciseID, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ExciseID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DocPath, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="file" id="file" />
            @Html.ValidationMessageFor(model => model.DocPath, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

RainbowWine/Views/DeliveryAgents/Delete.cshtml
@model RainbowWine.Data.DeliveryAgent

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DeliveryAgent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DeliveryExecName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveryExecName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastDeliveryOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastDeliveryOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contact)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contact)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TravelMode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TravelMode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Coverage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Coverage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAtShop)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAtShop)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExciseID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExciseID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DocPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DocPath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeliverySlot.DeliverySlotID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliverySlot.DeliverySlotID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WineShop.ShopName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WineShop.ShopName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RainbowWine/Views/DeliveryAgents/List.cshtml
@model IEnumerable<RainbowWine.Data.DeliveryAgent>

@{
    ViewBag.Title = "List";
    string track = "";
}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap.min.css">
<script src="~/Scripts/jquery.min.js"></script>
<script src="~/Scripts/jquery-ui.js"></script>
<script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap.min.js"></script>



<h2>List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<p>
    <input type="text" placeholder="Shop Name" id="txtShopSearch" value="@ViewBag.ShopName" />
    @Html.DropDownList("dpShopId", (IEnumerable<SelectListItem>)@ViewBag.ShopId, "Select Shop", htmlAttributes: new { @class = "form-control", @id = "dpShopId", @style = "display:none;" })

    <input type="text" placeholder="Delivery Agent Name" id="txtDeliveryAgentSearch" value="@ViewBag.AgentName" />
    @Html.DropDownList("dpAgentId", (IEnumerable<SelectListItem>)@ViewBag.AgentId, "Select Agent", htmlAttributes: new { @class = "form-control", @id = "dpAgentId", @style = "display:none;" })

    <button id="btnSearch"> Search</button>
    <input type="button" value="Track All Agents" target="_blank" onclick="window.open('@Url.Action("TrackAllAgents", "DeliveryAgents")','_blank')" />
    <div> @*@Html.ActionLink("Track All Agents", "TrackAllAgents", new { controller = "DeliveryAgents" }, new { target = "_blank" })*@</div>
</p>
<table class="table table-striped table-bordered" id="listtable">
    <thead>
        <tr>
            <th>
                Delivery Agenet Name
            </th>
            <th>
                Last Delivery On
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contact)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WineShop.ShopName)
            </th>
            <th>
                On/Off
            </th>
            <th>
                Zone Name
            </th>
            <th>
                On Date
            </th>
            <th>
                Off Date
            </th>
            <th>
                IsActive
            </th>
            <th></th>
        </tr>

    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DeliveryExecName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastDeliveryOn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Contact)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.WineShop.ShopName)
                </td>
                <td>
                    @{
                        DateTime dt = DateTime.Now;
                        var delogin = item.DeliveryAgentLogins.Where(o => o.OnDuty.Year == dt.Year && o.OnDuty.Month == dt.Month && o.OnDuty.Day == dt.Day);
                        string onoff = (delogin.Count() > 0) ? "On" : "Off";
                        var todayLog = delogin?.FirstOrDefault();

                    }
                    <font style="color:@(onoff == "On" ? "green" : "red")"> <b>@onoff</b></font>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DeliveryZone.ZoneName)
                    @*@foreach (var zoneItem in item.WineShop.DeliveryZones)
                        {
                            @(zoneItem.ZoneName + ", ")
                        }*@
                </td>
                <td>
                    @{if (todayLog != null) { todayLog.OnDuty.ToString(); }
                    }
                </td>
                <td>
                    @{if (todayLog != null) { todayLog.OffDuty.ToString(); }
                    }
                </td>
                <td>
                    <a href="#" class="ankYesNo" lang="@item.Id">
                        @{
                            @(item.isActive == 0 ? "Yes" : "No")
                        }
                    </a>
                </td>
                <td>
                    @if (ViewBag.TrackDelAgent != null)
                    {
                        track = ViewBag.TrackDelAgent.Replace("deliveryAgentId", item.Id.ToString());

                    }
                    @Html.ActionLink("Edit", "ListEdit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "ListDetails", new { id = item.Id }) |
                    @Html.ActionLink("Login Details", "LoginDetails", new { id = item.Id }) |
                    @Html.ActionLink("Track Agent", "TrackDelAgent", new { controller = "DeliveryAgents", id = item.Id }, new { target = "_blank" })
                </td>
            </tr>
        }

    </tbody>

    
</table>
@section scripts{
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>

        $(document).ready(function () {
            $.noConflict();
            $('#listtable').DataTable({
                "searching": true,
                "lengthChange": false
            });
        });


        $("#txtShopSearch").autocomplete({
            source: function (request, response) {
                $('#dpShopId').val('').attr("selected", "selected");
                $.ajax({
                    url: "/orders/SearchShop",
                    data: {
                        text: request.term
                    },
                    success: function (data) {
                        console.log(data);
                        response($.map(data, function (item) {
                            console.log(item);
                            return { label: item.Name, value: item.Name, Id: item.Id };
                        }))
                    }
                });
            },
            minLength: 2,
            select: function (event, ui) {
                console.log("Selected: " + ui.item.value + " aka " + ui.item.label + " Id " + ui.item.Id);

                $('#dpShopId').val(ui.item.Id).attr("selected", "selected");
            }
        });
        $("#txtDeliveryAgentSearch").autocomplete({
            source: function (request, response) {
                $('#dpAgentId').val('').attr("selected", "selected");
                $.ajax({
                    url: "/orders/SearchDeliveryAgent",
                    data: {
                        text: request.term
                    },
                    success: function (data) {
                        response($.map(data, function (item) {
                            console.log(item);
                            return { label: item.Name, value: item.Name, Id: item.Id };
                        }))
                    }
                });
            },
            minLength: 2,
            select: function (event, ui) {
                console.log("Selected: " + ui.item.value + " aka " + ui.item.label + " Id " + ui.item.Id);
                $('#dpAgentId').val(ui.item.Id).attr("selected", "selected");
            }
        });
        $('#btnSearch').click(function () {
            var shopname = $('#txtShopSearch').val();
            var shop = $('#dpShopId').val();
            var agentname = $('#txtDeliveryAgentSearch').val();
            var agent = $('#dpAgentId').val();
            window.location = "/DeliveryAgents/List?shop=" + shop + "&shopname=" + shopname + "&agent=" + agent + "&agentname=" + agentname;
        })
        $('.ankYesNo').click(function () {

            if (confirm("Are you sure do you want to change the status.")) {
                $.post("/DeliveryAgents/UpdateDelAgentStatus",
                    {
                        "id": $(this).attr('lang')
                    },
                    function (data) {
                        console.log(data);
                        if (data != undefined) {
                            alert(data.msg);
                            window.location.reload();
                        }
                    }
                );
            }
            return false;
        })
    </script>
}

RainbowWine/Views/DeliveryAgents/TrackAllAgents.cshtml
@{
    ViewBag.Title = "TrackAllAgents";
}
<h2>Track All Agents</h2>
<div class="embed-responsive embed-responsive-16by9">
    <iframe src="@ViewBag.TrackAllDelAgent" style="
      overflow: hidden;
      overflow-x: hidden;
      overflow-y: hidden;
      height: 100%;
      width: 100%;
      position: absolute;
      top: 120px;
      left: 0px;
      right: 0px;
      bottom: 0px;
    " allowfullscreen title="Iframe Example"></iframe>
</div>