RainbowWine/Controllers/ManufacturerController.cs
using PagedList;
using RainbowWine.Data;
using RainbowWine.Services.DBO;
using RainbowWine.Services.DO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RainbowWine.Controllers
{
    [Authorize(Roles = "Shopper")]
    public class ManufacturerController : Controller
    {
        private rainbowwineEntities db = new rainbowwineEntities();
        ManufacturerDBO manufacturerDBO = new ManufacturerDBO();
        // GET: Manufacturer
        public ActionResult Index(int? page)
        {
            int pageSize = 6;
            int pageNumber = (page ?? 1);
            var res= manufacturerDBO.GetManufacturer();

            return View(res.ToPagedList(pageNumber, pageSize));
        }

        [HttpPost]
        public ActionResult UpdateManufacturer(int manufacturerId, string manufacturerName, string manufacturerAbbreviated, string region, string collabSince)
        {
            int res = 0;
            try
            {
               res= manufacturerDBO.ManufacturerUpdate(manufacturerId, manufacturerName, manufacturerAbbreviated, region, collabSince);
            }
            catch (Exception ex)
            {
                return Json(new { status = false, msg = "error" }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { response = res, status = true, msg = "udpate" }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult AddManufacturer(string manufacturerName, string manufacturerAbbreviated, string region, string collabSince)
        {
            int res = 0;
            try
            {
              res=  manufacturerDBO.ManufacturerAdd(manufacturerName, manufacturerAbbreviated, region, collabSince);
            }
            catch (Exception ex)
            {
                return Json(new { status = false, msg = "error" }, JsonRequestBehavior.AllowGet);
            }
            return Json(new {response=res, status = true, msg = "udpate" }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult DeleteManufacturer(int manufacturerId = 0)
        {

            try
            {
               
                manufacturerDBO.ManufacturerDelete(manufacturerId);
            }
            catch (Exception ex)
            {
                return Json(new { status = false, msg = "error" }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { status = true, msg = "udpate" }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult BrandManufacturer(int id)
        {
            IList<BrandManufacturerDO> brandManufacturerDO = null;
            IList<BrandManufacturerDO> singleList = null;
            ManufacturerDBO manufacturerDBO = new ManufacturerDBO();
            brandManufacturerDO = manufacturerDBO.GetBrandManufacturerById(id);
            singleList = manufacturerDBO.GetBrandManufacturerDetail(id);
            ViewBag.ManufacturerName = singleList.FirstOrDefault().ManufacturerName;
            ViewBag.Id = id;
            ViewBag.AllBrandManufacturerList = new SelectList(singleList, "BrandId", "BrandName");
            ViewBag.SingleBrandManufacturer = new SelectList(singleList, "BrandId", "BrandName");
            return View(brandManufacturerDO);
        }

        [HttpGet]
        public ActionResult BrandManufacturerList()
        {
            ManufacturerDBO manufacturerDBO = new ManufacturerDBO();
            IList<BrandManufacturerDO> brandManufacturerDO = null;
            brandManufacturerDO = manufacturerDBO.GetBrandManufacturerDetail(0);
            IEnumerable<IGrouping<string, BrandManufacturerDO>> groups = brandManufacturerDO.GroupBy(x => x.ManufacturerName);
            var res = groups;
            ViewBag.ProductList = new SelectList(res, "BrandId", "BrandName");
            return View(groups);
        }

        [HttpPost]
        public JsonResult AddAndUpdateBrandManufacturer(int manufacturerId, string[] brandIds, string action)
        {
            var u = db.AspNetUsers.Where(o => o.Email == User.Identity.Name).FirstOrDefault();
            ManufacturerDBO manufacturerDBO = new ManufacturerDBO();
            string ids = String.Join(",", brandIds);
            var prods = manufacturerDBO.AddAndUpdateBrandManufacturer(manufacturerId, ids, u.Email, action);

            return Json(new { ComBrandManufacturer = prods });
        }

        [HttpPost]
        public JsonResult AddNewBrandManufacturer(string manufacturerId, string[] brandIds, string action)
        {
            var u = db.AspNetUsers.Where(o => o.Email == User.Identity.Name).FirstOrDefault();
            ManufacturerDBO manufacturerDBO = new ManufacturerDBO();
            string mId = String.Join(",", manufacturerId);
            string ids = String.Join(",", brandIds);
            var prods = manufacturerDBO.AddAndUpdateBrandManufacturer(Convert.ToInt32(mId), ids, u.Email, action);

            return Json(new { ComBrandManufacturer = prods });
        }

        [HttpGet]
        public ActionResult AddBrandManufacturer()
        {
            IList<BrandManufacturerDO> brandManufacturerDO = null;
            //IList<BrandManufacturerDO> allBrandManufacturerList = null;
            ManufacturerDBO manufacturerDBO = new ManufacturerDBO();
            brandManufacturerDO = manufacturerDBO.GetBrandManufacturerById(0);
            var allBrandList = db.ProductBrands.ToList();
            ViewBag.NotLinkBrandManufacturerList = new SelectList(brandManufacturerDO, "ManufacturerId", "ManufacturerName");
            ViewBag.AllBrandManufacturerList = new SelectList(allBrandList, "ProductBrandId", "BrandName");
            return View(brandManufacturerDO);
        }

        
    }

    
}

RainbowWine/Views/Manufacturer/AddBrandManufacturer.cshtml
@model IEnumerable<RainbowWine.Services.DO.BrandManufacturerDO>

<h2>Add New Brand Manufacturer</h2>
<div>
    <br />
    <div>
        <b>Manufacturer</b>
        <select id="NotLinkBrandManufacturerlistId" size="10" required=required name="NotLinkBrandManufacturerlistlist">
            @if (ViewBag.NotLinkBrandManufacturerList != null)
            {
                foreach (var item in ViewBag.NotLinkBrandManufacturerList)
                {
                    if (item.Text != null)
                    {
                        <option value="@item.Value">@item.Text</option>

                    }

                }

            }
        </select>
        <b>Brands</b>
        <select id="BrandManufacturerlistId" multiple="multiple" required=required name="BrandManufacturerlist">
            @if (ViewBag.AllBrandManufacturerList != null)
            {
                foreach (var item in ViewBag.AllBrandManufacturerList)
                {
                    if (item.Text != null)
                    {
                        <option value="@item.Value">
                            @item.Text
                        </option>

                    }
                }
            }
        </select>
    </div>
    
</div>
<br />
<br />
<button id="btnSave">Save</button>


@section scripts{


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" />
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js">
    </script>
    <script type="text/javascript">
        $(function () {
            $("#NotLinkBrandManufacturerlistId").select2({
                placeholder: '--Select Manufacturer--',
                width: '20%',
                theme: "classic"
            });
        });

        $(function () {
            $("#BrandManufacturerlistId").select2({
                placeholder: '--Select Brands--',
                closeOnSelect: false,
                width: '50%',
            });
        });

    </script>

    <script>

        $('#btnSave').on('click', function () {
            var Manufacturer = $("#NotLinkBrandManufacturerlistId option:selected");
            var selected = $("#BrandManufacturerlistId option:selected");    /*Current Selected Value*/
            var message = "";
            var arrManufacturer = [];      /*Array to store multiple values in stack*/
            Manufacturer.each(function () {
                arrManufacturer.push($(this).val());    /*Stack the Value*/
                message += $(this).text() + " " + $(this).val() + "\n";

            });

            var arrSelected = [];      /*Array to store multiple values in stack*/
            selected.each(function () {
                arrSelected.push($(this).val());    /*Stack the Value*/
                message += $(this).text() + " " + $(this).val() + "\n";

            });


            if (arrManufacturer == null || arrManufacturer == "") {
                alert("Please select Manufacturer");
                return false;
            }

            if (arrSelected == null || arrSelected == "") {
                alert("Please select Brands");
                return false;
            }
            $.post(
                '/Manufacturer/AddNewBrandManufacturer/',
                { manufacturerId: arrManufacturer, brandIds: arrSelected, action: "AddNewEntry" },
                function (item) {
                    alert("New Brand Added With Manufacturer Successfully");
                    window.location.reload();
                }, "json");
        });
    </script>
}

RainbowWine/Views/Manufacturer/BrandManufacturer.cshtml
@model IEnumerable<RainbowWine.Services.DO.BrandManufacturerDO>

<h2>Brand Manufacturer</h2>
Manufacturer Name <b>:</b> <label id="lblProductName">@ViewBag.ManufacturerName</label> <label id="lblManufacturerId" style="display:none">@ViewBag.Id</label>
<h3>Add  Brand Manufacturer</h3>
<div>
    <br />
    Brand Manufacturer
    <select id="allBrandManufacturerlistId" multiple="multiple" required=required name="allBrandManufacturerlist" size="10" class="4col formcls">
        @if (ViewBag.AllBrandManufacturerList != null)
        {
            foreach (var item in ViewBag.AllBrandManufacturerList)
            {
                if (item.Text != null)
                {
                    <option selected="selected" disabled="disabled" class="ms-elem-selectable" value="@item.Value">@item.Text</option>

                }

            }
            foreach (var item in Model)
            {
                if (item.BrandName != null)
                {
                    <option value="@item.BrandId">
                        @item.BrandName
                    </option>

                }

            }
        }
    </select>
    <button id="btnSave">Save</button>
</div>
<br />
<br />
<h3>Remove BrandManufacturer</h3>

<div>
    <br />
    Brand Manufacturer
    <select id="BrandManufacturerlistId" multiple="multiple" required=required name="BrandManufacturerlist" class="4col formcls">
        @if (ViewBag.SingleBrandManufacturer != null)
        {
            foreach (var item in ViewBag.SingleBrandManufacturer)
            {
                if (item.Text != null)
                {
                    <option value="@item.Value">
                        @item.Text
                    </option>

                }
            }
        }
    </select>
    <button id="btnUpdate">Update</button>
</div>


<style>
    .ms-options-wrap > .ms-options > ul label {
        position: relative;
        display: inline-block;
        width: 100%;
        padding: 4px;
        margin: 1px 0;
        background-color: #9DCEFF;
    }

        .ms-options-wrap > .ms-options > ul li.selected label,
        .ms-options-wrap > .ms-options > ul label:hover {
            background-color: #003A75;
            color: #fff;
        }
</style>

@section scripts{

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.16/js/bootstrap-multiselect.min.js" integrity="sha512-ljeReA8Eplz6P7m1hwWa+XdPmhawNmo9I0/qyZANCCFvZ845anQE+35TuZl9+velym0TKanM2DXVLxSJLLpQWw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.16/css/bootstrap-multiselect.css" integrity="sha512-DJ1SGx61zfspL2OycyUiXuLtxNqA3GxsXNinUX3AnvnwxbZ+YQxBARtX8G/zHvWRG9aFZz+C7HxcWMB0+heo3w==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <script>
        $(function () {
            $('#allBrandManufacturerlistId').multiselect({
                includeSelectAllOption: true,
                nonSelectedText: '--Select BrandManufacturer--', //"Select Competitor", /*To enable the Select all Option*/
                selectAllValue: 'multiselect-all',     /*The value used for the select all option can be configured using the selectAllValue*/
                enableFiltering: true,   /*A filter input will be added to dynamically filter all the options*/
                enableCaseInsensitiveFiltering: true,  /*To enable Case Insenstitive Filtering (Upper and Lower Case Letters)*/
                maxHeight: '200',
                buttonWidth: '200'
                

            });
        });

        $(function () {
            $('#BrandManufacturerlistId').multiselect({
                columns: 1,
                includeSelectAllOption: true,
                nonSelectedText: '--Select BrandManufacturer--', /*To enable the Select all Option*/
                selectAllValue: 'multiselect-all',     /*The value used for the select all option can be configured using the selectAllValue*/
                enableFiltering: true,   /*A filter input will be added to dynamically filter all the options*/
                enableCaseInsensitiveFiltering: true,  /*To enable Case Insenstitive Filtering (Upper and Lower Case Letters)*/
                maxHeight: '200',
                buttonWidth: '200',


            });
        });
    </script>

    <script>

        $('#btnSave').on('click', function () {
            var selected = $("#allBrandManufacturerlistId option:selected");    /*Current Selected Value*/
            var message = "";
                var arrSelected = [];      /*Array to store multiple values in stack*/
            selected.each(function () {
                    arrSelected.push($(this).val());    /*Stack the Value*/
                    message += $(this).text() + " " + $(this).val() + "\n";

            });
            var ManufacturerId = $("#lblManufacturerId").text();
            if (arrSelected == null || arrSelected == "") {
                alert("Please select BrandManufacturer from dropdown");
                return false;
            }
            $.post(
                '/Manufacturer/AddAndUpdateBrandManufacturer/',
                { manufacturerId: ManufacturerId, brandIds: arrSelected,action: "Add" },
                function (item) {
                    alert("BrandManufacturer Added Successfully");
                    window.location.reload();
                }, "json");
        });

        $('#btnUpdate').on('click', function () {
            var selected = $("#BrandManufacturerlistId option:selected");    /*Current Selected Value*/
            var message = "";
            var arrSelected = [];      /*Array to store multiple values in stack*/
            selected.each(function () {
                arrSelected.push($(this).val());    /*Stack the Value*/
                message += $(this).text() + " " + $(this).val() + "\n";
            });
            var ManufacturerId = $("#lblManufacturerId").text();
            if (arrSelected == null || arrSelected == "") {
                alert("Please select BrandManufacturer from dropdown");
                return false;
            }
            $.post(
                '/Manufacturer/AddAndUpdateBrandManufacturer/',
                { manufacturerId: ManufacturerId, brandIds: arrSelected, action: "Update" },
                function (item) {
                    alert("BrandManufacturer Updated Successfully");
                    window.location.reload();
                }, "json");
        });
    </script>

}

RainbowWine/Views/Manufacturer/BrandManufacturerList.cshtml
@model IEnumerable<IGrouping<string, RainbowWine.Services.DO.BrandManufacturerDO>>
@{
    ViewBag.Title = "Brand Manufacturer List";
    var Id = 0;
}

<h2>Brand Manufacturer List</h2>
<h3>
    @Html.ActionLink("Competitor Product List", "ProductCompetitorLinkList", "Orders")
</h3>
<h4>
    @Html.ActionLink("Add New Brand With Manufacturer", "AddBrandManufacturer", "Manufacturer")
</h4>
<table class="table-bordered" width="100%" cellspacing="0">
    <thead class="bg-success">
        <tr>
            <td>
                Manufacturer Name
            </td>

            <td>
                Brand Name
            </td>
            <td>Action</td>
        </tr>
        </thead>
        @foreach (var groupingByClassA in Model)
        {
<tbody>
    <tr>
        <td>
            @groupingByClassA.Key

        </td>
        <td>
            @foreach (var classA in groupingByClassA)
            {
                <table>
                    <tr>
                        <td>
                            @Html.DisplayFor(modelitem => classA.BrandName)

                        </td>
                    </tr>
                </table>
                Id = classA.ManufacturerId;
            }
        </td>
        <td>
            @Html.ActionLink("Edit", "BrandManufacturer", new { id = Id })
            @(" ")
        </td>
    </tr>
</tbody>
        }
</table>

RainbowWine/Views/Manufacturer/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<RainbowWine.Services.DO.ManufacturerDO>
@*@model IEnumerable<RainbowWine.Services.DO.ManufacturerDO>*@
@{
    ViewBag.Title = "Manufacturer";

}

<h2>Manufacturer</h2>
<div id='Paging' style="text-align:center">
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))

</div>
<p></p>

<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
    <thead class="bg-success">
        <tr>
            <th>
                Manufacturer Name
            </th>
            <th>
                Manufacturer Abbreviated
            </th>
            <th>
                Region
            </th>
            <th>
                CollabSince
            </th>
            <th>Action</th>
        </tr>
    </thead>

    @foreach (var item in Model)
    {
        <tbody>
            <tr>
                <td>
                    @Html.Label(item.ManufacturerName.ToString(), new { @class = "display-mode", @id = "txtManufacturerNameId" })
                    @Html.TextBox("ManufacturerName-Edit", item.ManufacturerName.ToString(), new { @class = "edit-mode", style = "width: 150px;" })

                </td>
                <td>
                    @Html.Label(item.ManufacturerAbbreviated.ToString(), new { @class = "display-mode", @id = "txtManufacturerAbbreviatedId" })
                    @Html.TextBox("ManufacturerAbbreviated-Edit", item.ManufacturerAbbreviated.ToString(), new { @class = "edit-mode", style = "width: 150px;" })

                </td>
                <td>
                    @Html.Label(item.Region.ToString(), new { @class = "display-mode", @id = "txtRegionId" })
                    @Html.TextBox("Region-Edit", item.Region.ToString(), new { @class = "edit-mode", style = "width: 150px;" })

                </td>
                <td>
                    @Html.Label(item.CollabSince.ToString(), new { @class = "display-mode", @id = "txtCollabSinceId" })
                    @Html.TextBox("CollabSince-Edit", item.CollabSince.ToString(), new { @class = "edit-mode", style = "width: 150px;" })

                </td>
                <td>
                    <button class="btn_grid edit-item display-mode" id="@item.ManufacturerId">Edit</button>
                    <button class="btn_grid delete-item display-mode" id="@item.ManufacturerId">Delete</button>
                    <button class="btn_grid save-item edit-mode" id="@item.ManufacturerId">Save</button>
                    <button class="btn_grid cancel-item edit-mode" id="@item.ManufacturerId">Cancel</button>
                </td>
            </tr>
        </tbody>
    }

</table>

<div>
    <table class="table table-bordered" width="100%" cellspacing="0">
        <tr>
            <td><input type="text" placeholder="Manufacturer Name" id="txtAddManufacturerName" /></td>
            <td><input type="text" placeholder="Manufacturer Abbreviated" id="txtAddManufacturerAbbreviated" /></td>
            <td> <input type="text" placeholder="Region" id="txtAddRegion" /></td>
            <td> <input type="text" placeholder="CollabSince" id="txtAddCollabSince" /></td>
            <td> <button id="btnAdd" class="display-mode">Add</button></td>
        </tr>
    </table>
</div>

<p>@Html.ActionLink("Back To Competitor", "ProductCompetitorLinkList", "Orders")</p>
@section scripts{
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $('#btnAdd').click(function () {
            var manufacturerName = $('#txtAddManufacturerName').val();
            var manufacturerAbbreviated = $('#txtAddManufacturerAbbreviated').val();
            var region = $('#txtAddRegion').val();
            var collabSince = $('#txtAddCollabSince').val();

            var prodId = $(this).attr('data-prod');
            console.log(prodId);
            if (manufacturerName == undefined || manufacturerName == '') { alert('Please enter manufacturerName') }
            else if (manufacturerAbbreviated == undefined || manufacturerAbbreviated == '') { alert('Please enter manufacturerAbbreviated') }
            else if (region == undefined || region == '') { alert('Please enter region') }
            else {
                if (confirm("Are you sure  you want to save manufacturer.")) {
                    $.post(
                        '/Manufacturer/AddManufacturer/',
                        { manufacturerName: manufacturerName, manufacturerAbbreviated: manufacturerAbbreviated, region: region, collabSince: collabSince },
                        function (item) {
                            if (item != undefined) {
                                if (item.response == 3) {
                                    alert('Manufacturer name is already exist.');
                                }
                                else if (item.status) {
                                    window.location.reload();
                                }
                                else {
                                    alert('Unable to add manufacturerName.');
                                }
                            }
                        }, "json");
                }
            }

        });

        $('.edit-mode').hide();
        $('.edit-item').on('click', function () {
            $('.edit-mode').hide();
            //$('.delete-mode').hide();
            $('.display-mode').show();
            var tr = $(this).parents('tr:first');
            tr.find('.edit-mode, .display-mode').toggle();
        });
        $('.cancel-item').on('click', function () {
            var tr = $(this).parents('tr:first');
            tr.find('.display-mode,.edit-mode').toggle();
        });
        $('.save-item').on('click', function () {
            //console.log("DD");
            var tr = $(this).parents('tr:first');
            var id = $(this).prop('id');
            var manufacturerName = tr.find('#ManufacturerName-Edit').val();
            var manufacturerAbbreviated = tr.find('#ManufacturerAbbreviated-Edit').val();
            var region = tr.find('#Region-Edit').val();
            var collabSince = tr.find('#CollabSince-Edit').val();
            if (confirm("Are you sure  you want to update manufacturer.")) {
                $.post(
                    '/Manufacturer/UpdateManufacturer/',
                    { manufacturerId: id, manufacturerName: manufacturerName, manufacturerAbbreviated: manufacturerAbbreviated, region: region, collabSince: collabSince },
                    function (item) {
                        if (item != undefined) {
                            if (item.response == 3) {
                                alert('Manufacturer name is already exist.');
                            }
                            else if (item.status) {
                                window.location.reload();
                            }
                            else {
                                alert('Unable to update the Manufacturer.');
                            }
                        }
                    }, "json");
                tr.find('.edit-mode, .display-mode').toggle();
            }
        });

        $('.delete-item').on('click', function () {
            if (confirm('Are you sure do you want to delete it?')) {
                //console.log("DD");
                var tr = $(this).parents('tr:first');
                var id = $(this).prop('id');
                var barcode = tr.find('#BarcodeId-Edit').val();
                $.post(
                    '/Manufacturer/DeleteManufacturer/',
                    { manufacturerId: id },
                    function (item) {
                        if (item != undefined) {
                            if (item.status)
                                window.location.reload();
                            else
                                alert('Unable to delete the barcode.');
                        }
                    }, "json");
            }
        });
    </script>
    <script language="javascript">
        $(function () {
            $('#choose').pagination({
                items: 20,
                itemsOnPage: 2,
                cssStyle: 'light-theme',
                onPageClick: function (pageNumber) { test(pageNumber) }
            });
        });
    </script>
}